[pytest]
testpaths = tests
addopts = -v -s
log_cli = true
log_cli_level = INFO

markers =
    e2e: end-to-end tests requiring browser and CAPTCHA

# Default url parameters
modality=Continuous
product=30
data_mode=table
market_area=GB
underlying_year=
technology=
period=
production_period=
sub_modality =
auction=
